### ISSUE TITLE
Schema Admin page is blank

### ISSUE THREAD

**Issue by albhardy** [mapcentia/geocloud2#10]
Hi,
I installed GC2 on new Ubuntu 14.04 LTS  according to Wiki installation guide.
However, my schema admin page is blank:

![image](https://cloud.githubusercontent.com/assets/1732018/5733476/810bd326-9bde-11e4-90b3-deaa448d32ce.png)

~~~
Failed to load resource: the server responded with a status of 500 (Internal Server Error) jquery.min.js?c1c829b72179d9c3:6 
Uncaught TypeError: Cannot read property 'fields' of undefined
http://[my server]/store/[username]/public Failed to load resource: net::ERR_CACHE_MISS
~~~
The apache error.log 
`FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Fatal error:  Call to a member function fetch() on a non-object in /var/www/geocloud2/app/inc/Model.php on line 36`

Not sure if it's relevant but `dbs.php` is unable to detect apache mod_rewrite and python installed.

![image](https://cloud.githubusercontent.com/assets/1732018/5733518/04f3ca5e-9bdf-11e4-9b58-cfcdd768a3c5.png)

Though the server has them working

![image](https://cloud.githubusercontent.com/assets/1732018/5733537/67dfc988-9bdf-11e4-8e7f-bece27a4dd89.png)

how can I resolve this?

**Comment by mapcentia** [comment]
Please try to migrate the databases by running this command:
cd /var/www/geocloud2/app/conf/migration/ && ./run

**Comment by albhardy** [comment]
Awesome! yes, it works perfectly!
