### ISSUE TITLE
Not possible to unset "line cap"

### ISSUE THREAD

**Issue by velle** [mapcentia/geocloud2#105]
When setting the class properties for a layer, there is a property called "line cap". Clicking it shows a drop down menu. But after having chosen one of those values, I believe there is no way of unsetting this. 

![image](https://user-images.githubusercontent.com/4488298/169563443-df110c88-06f0-45eb-9f0a-aa69a17ac758.png)

**Comment by mapcentia** [comment]
Line cap always has a value and the default is "round". Closing this for #106
