### ISSUE TITLE
WFS-T implementation erronous dimensions

### ISSUE THREAD

**Issue by giovanniborella** [mapcentia/geocloud2#109]
We're currently experiencing some oddities when requesting 3D features through WFS endpoint.

When adding the endpoint to qgis, the order of coordinates is misinterpreted, with the Z-coordinate beeing set as the next vertex' X-coordinate. Resulting in less than logical geometry. See attached images:

![billede](https://user-images.githubusercontent.com/18160930/172833071-47f5ab01-5fb9-4508-a423-68374231aa13.png)

![billede](https://user-images.githubusercontent.com/18160930/172833475-7f5cf281-8d4f-4fda-a5a0-1cfbbbe2bcf1.png)

The same tables, through OWS endpoint apper fine.

**Comment by mapcentia** [comment]
I guess it's because the gml:posList lacks dimension attribute

**Comment by mapcentia** [comment]
Fixed in bc3c4cd
