### ISSUE TITLE
What is the best practice to load structured plain text or CSV ?

### ISSUE THREAD

**Issue by des2015** [mapcentia/geocloud2#11]
Many files today have structured plain text rows. One column in the file can be geocoded (IPs, postal codes, addresses, etc) into two values (lan,lat) with the help of internal server SQL database. So, please, tell GC2 users about the best practice to geocode such file into supported format or even fully automate the uploading process into GC2 databases.

**Comment by mapcentia** [comment]
Text file import is coming to GC2 soon. Often is QGIS (or similar) used for converting text files to e.g. GML for uploading to GC2. But we are now building this function into GC2.

**Comment by mapcentia** [comment]
It took a while, but now csv upload is possible thanks to GDAL2.
