### ISSUE TITLE
2022.5 memcache minor breakage

### ISSUE THREAD

**Issue by giovanniborella** [mapcentia/geocloud2#113]
Memcache was introduced in https://github.com/mapcentia/geocloud2/commit/71ce330d4052f02eb20422267eddbd5a3d564b04, however when built, there is no check for memcache being in the supplied environment - resulting in a faliure to launch apache2.

I've removed following locally:
https://github.com/mapcentia/geocloud2/blob/82d8931883ff020a562a6451ae288ac431e654cc/app/controllers/Mapcachefile.php#L100-L105
To get apache booting again.

**Comment by mapcentia** [comment]
Memcache doesn't actual have to be installed, but MapCache has to be built with Memcache support. I'm not sure if you can check this. So it's important to built new image using the latest Dockerfile when updating the GC2 source. In any case it always a good idea to built new image when upgrading.
