### ISSUE TITLE
Upgrade Traefik to version 2

### ISSUE THREAD

**Issue by BoMarconiHenriksen** [mapcentia/geocloud2#116]

**Comment by BoMarconiHenriksen** [comment]
@mapcentia you can assign me to this issue. If you have any insights in updating to Traefik version 2 please let me know.

**Comment by mapcentia** [comment]
This is on my todo, but I haven't got to it yet.

**Comment by BoMarconiHenriksen** [comment]
@mapcentia You can close this issue. I have moved it to https://github.com/mapcentia/dockerfiles/issues/11 - I guess it make more sense to upgrade Traefik there.
