### ISSUE TITLE
Possibility to show / query table of attributes in public maps ?

### ISSUE THREAD

**Issue by rajanski** [mapcentia/geocloud2#12]
Hi, geocloud2 is great! Is abovementioned feature missing or am i just not seeing it? 

Kind regards

**Comment by mapcentia** [comment]
Thanks! You can click on a feature on a visible layer in the Viewer: http://snag.gy/9NwpE.jpg

Or this it something else you're missing?

**Comment by rajanski** [comment]
Hi no what I meant is the possibility to show the entire attribute table of a layer

**Comment by mapcentia** [comment]
You can't show the whole attribute table in a public - only in the Map tab inside Admin. But you can make an enhancement request.
