### ISSUE TITLE
Tiles not found

### ISSUE THREAD

**Issue by davijo** [mapcentia/geocloud2#13]
Hi,

I am having difficulties figuring out what might be causing this kind of behaviour:
![image](https://cloud.githubusercontent.com/assets/8625487/7983872/554c744e-0acd-11e5-9b69-3cbfe1c6e018.png)

The dataset is the one from here:
https://www.avoindata.fi/data/en/dataset/helsingin-kaupunginosat/resource/24992d48-8e64-4337-8464-2c19f0dbc86d

Also I cannot seem to be able to draw the outlines on top of the map layer. Clicking however seems to be working.

Any ideas where to look further?

**Comment by mapcentia** [comment]
Hi, the pink tiles indicates that an error is sent instead of a tile. Try to add a "Single" style to the layer and see whats happens. By the look of your screendump the data seems to has been imported alright.



Martin Høgh

mapcentia.com
+45 26277810
Skype: mhoegh1
about.me/mhoegh
