### ISSUE TITLE
Docker Error

### ISSUE THREAD

**Issue by hrishiballal** [mapcentia/geocloud2#134]
Hello, 
I am running the latest local docker instance via the Docker compose instructions and I am getting a "Google error" attached. I think that GC2 expects a Google API key but how to specify a API key? This is preventing the User Interface to be loaded. Would appreciate any help. 

![google](https://user-images.githubusercontent.com/1588744/232467368-ef788f1d-83a1-4676-b866-4f11d4389ecc.jpg)

**Comment by mapcentia** [comment]
@hrishiballal It's some change Google has made in the API- I've pushed a new GC2 Docker image without Google Maps enabled. Just do:

```docker pull mapcentia/gc2core```

And re-run the compose file.

Thanks for reporting the issue!

**Comment by hrishiballal** [comment]
Confirming that this is fixed now.
