### ISSUE TITLE
Errors while creating a new user on latest images

### ISSUE THREAD

**Issue by hrishiballal** [mapcentia/geocloud2#137]
Hello I just updated the docker images on my side, but when creating a new user, I am seeing errors below. Would appreciate any pointers on how to fix it. 

![gc2-error](https://github.com/mapcentia/geocloud2/assets/1588744/888ad394-b014-4af9-ad70-bba9fc0b4cf5)

**Comment by mapcentia** [comment]
Could you check the response from the server in the browser developer consol?

**Comment by hrishiballal** [comment]
Hello @mapcentia thank you for this, how do you mean? There is no errors, I am using the docket compose script to pull the latest images l.

**Comment by mapcentia** [comment]
Is in the browser developer tools. When you create a new user, the page will make a POST request. It returns an error in your case. Take a look at the image. Here I got an error because the user already exists. This is an excepted error, but yours is not. I guess the response has some info about the error:

![image](https://github.com/mapcentia/geocloud2/assets/3850918/2cd8056a-cedf-4e24-b26f-8d8c6f540aa9)

**Comment by hrishiballal** [comment]
![screenshot](https://github.com/mapcentia/geocloud2/assets/1588744/68806972-070d-499d-889c-d8a9a47fad2d)

This happens even I have used `docker system prune` and also `docker volume prune`

**Comment by mapcentia** [comment]
When creating a new user, GC2 will create a database and a role (with the same name). For some reason  something went wrong and GC2 tried to clean up by dropping the user role, which was created in the process (or already existing, which may be the cause of the error). But it can't, because the user owns objects in another database?

Is your new user name the same as an already existing user role in the database?

I think I'll take a look on the process of creating the GC2 users. This has happen before and leaves a bit of a mess.

**Comment by hrishiballal** [comment]
Yes correct the screenshot is when I use a username that is already exists, the error is same when I try to create a new username that does not exist. I had a existing version, I brought it down and updated the images.

**Comment by mapcentia** [comment]
You get an error even when using a completely new name? As never used before?

**Comment by hrishiballal** [comment]
Thats correct, I did a totally fresh installation  and here is a new error, BTW I am using `docker compose down --volumes` to ensure that all volumes are also deleted

![image](https://github.com/mapcentia/geocloud2/assets/1588744/ac3614f3-e2f8-45bf-8e70-025509d1023a)

**Comment by mapcentia** [comment]
I've gone through the Docker images and  compose file https://github.com/mapcentia/gc2-vidi-docker-compose

It should work now - I've tested on a freshly installed Ubuntu 24.04.

Remove old images and volumes

`docker compose down --volumes` should do it

Then `docker system prune -a`

**Comment by hrishiballal** [comment]
Thank you for this, I am however getting the same error, fresh install of Ubuntu 24.04 and following your instructions. 

![image](https://github.com/mapcentia/geocloud2/assets/1588744/aec617a3-fc57-4d30-941f-eb27947187b0)

**Comment by mapcentia** [comment]
Could you try to pull the image:

`docker pull mapcentia/gc2core8`

And then `docker compose down` and `docker compose up`

**Comment by hrishiballal** [comment]
Thank you for this, it is still creating an issue for me, sharing steps / screenshots
##### Step 1
![p1](https://github.com/mapcentia/geocloud2/assets/1588744/5d4db7ed-f688-4d61-9ed3-e744c8ae7806)
##### Step 2
![p2](https://github.com/mapcentia/geocloud2/assets/1588744/948d8517-5a57-4655-bee2-ee7b06e90041)
##### Step 3
![p3](https://github.com/mapcentia/geocloud2/assets/1588744/aaf53992-6e00-4e70-b024-9c5fff42e02b)
##### Step 4
![p4](https://github.com/mapcentia/geocloud2/assets/1588744/c2580d41-7f2b-4cf3-bb3f-708ce05d2f4b)
##### Step 5
![p5](https://github.com/mapcentia/geocloud2/assets/1588744/6fde3873-4ddf-4b6a-9d98-d56e3cf759a8)
##### Step 6
![p6](https://github.com/mapcentia/geocloud2/assets/1588744/b75e04c8-4ae5-486d-a53c-f969472349bc)

**Comment by mapcentia** [comment]
Did you git pull the latest https://github.com/mapcentia/gc2-vidi-docker-compose ?

We're still finding and fixing bugs in the new GC2 Docker, so please pull gc2core again

**Comment by hrishiballal** [comment]
Hello @mapcentia , I have done it but still encountering the same issue, I am trying to revert to the old docker compose file and see if it works. Thanks again!

**Comment by hrishiballal** [comment]
I just tested with the latest repo and docker compose on my second machine with Windows + WSL and Docker and it all works no problems. For some reason it is not working on Ubuntu. I will investigate more.

**Comment by hrishiballal** [comment]
When I run it on linux server the following error is shown

![image](https://github.com/mapcentia/geocloud2/assets/1588744/8fb3cdfb-4761-4f2c-a4fa-b261c196bcfb)

and an additional error when launching for the first time (perhaps not relevant at this point)
![image](https://github.com/mapcentia/geocloud2/assets/1588744/6ddc812f-4407-43e2-b91f-138b1137f733)

**Comment by mapcentia** [comment]
I see the problem now. Migrations is not run on first startup because of the pg_hba.conf error. Could you check, that the  mapcentia/postgis15 image is used? It should have digest: sha256:4cfbacc93cb2564104b0c8d16a6ee0ca73c82c8f8feb24bf2eb59c4b82e28050

**Comment by hrishiballal** [comment]
Hello @mapcentia I updated the image: 
![image](https://github.com/mapcentia/geocloud2/assets/1588744/30a42408-3151-4866-b187-0d868f55f83b)
but getting the same error: 
![image](https://github.com/mapcentia/geocloud2/assets/1588744/940b23fe-4627-40a0-98b8-6ddaeb10577c)

Is there something I should change in the docker compose?

**Comment by hrishiballal** [comment]
I got it! changing [Line 56](https://github.com/mapcentia/gc2-vidi-docker-compose/blob/main/docker-compose.yml#L56) to `127.0.0.1` instead of `localhost` works 

![image](https://github.com/mapcentia/geocloud2/assets/1588744/4fe1b009-f391-4c62-a0f2-c282b0119f31)

**Comment by mapcentia** [comment]
Oh, thanks for keep trying. I've updated the file. It's strange why it works on some systems. Then I look at `/etc/hosts` inside the postgis15 container I see these lines:

```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
```
I guess your file is missing the first?

Docker write this file, so maybe it's a Docker thing. I'll keep from using `localhost` in Docker, because it's not sure it's matched to `127.0.0.1`
