### ISSUE TITLE
Can't create new user

### ISSUE THREAD

**Issue by geodyj** [mapcentia/geocloud2#138]
I use the latest docker compose to install gc2, and can't create new user.
![image](https://github.com/mapcentia/geocloud2/assets/22827404/13f1345f-08e0-444f-8407-24bb7bb4c3e3)
{
    "success": false,
    "message": "SQLSTATE[42703]: Undefined column: 7 ERROR:  column \"usergroup\" of relation \"users\" does not exist\nLINE 1: INSERT INTO users (screenname,pw,email,parentdb,usergroup,zo...\n                                                        ^",
    "test": null,
    "code": 400,
    "_execution_time": 0.357
}

**Comment by mapcentia** [comment]
I think it's because of a bug in the database migration script, so some fields are not created (like usergroup)

I'll patch this

**Comment by mapcentia** [comment]
I've updated the docker-compose file: https://github.com/mapcentia/gc2-vidi-docker-compose

So do a git pull

Do `docker compose down -v` and remove existing Docker images.

When `docker compose up`

The `postgis` service will now persist data.

**Comment by geodyj** [comment]
However, I got error again. like this:
 ✘ gc2core Error                                                                                                                                                        33.1s 
Error response from daemon: pull access denied for mapcentia/gc2core8, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by mapcentia** [comment]
mapcentia/gc2core8 is the new PHP8.3 image, which was still private. It's public now

**Comment by mapcentia** [comment]
I went trough the Docker images and https://github.com/mapcentia/gc2-vidi-docker-compose

Please upgrade everything (pull new images and delete volumes)

**Comment by geodyj** [comment]
It's OK now , thank you. By the way, could I change the Dark theme, font size and language of the Web UI ? and how to do that?

**Comment by mapcentia** [comment]
The language is set from your browsers settings, but it's only English and Danish, which are fully supported. Italian, Spanish, French and Russian are partly supported (English words where no translation exists).

There is only the dark theme.
