### ISSUE TITLE
Custom mapping when indexing in Elasticsearch

### ISSUE THREAD

**Issue by ballerupgis** [mapcentia/geocloud2#17]
Is it possible to create a custom mapping when indexing in ElasticSearch, when the default mapping is not satisfying? It would be nice to be able to select mapping types for the table columns before indexing. Fx. window with dropdown for every column, where core mapping types could be selected.  

Maybe it should also be able to set: "index" : "not_analyzed"

**Comment by mapcentia** [comment]
The feature is planned to be implemented. It'll also be possible to define custom analyzers, by drop a Elasticsearch "settings" json in the conf dir.

There will be two dropdowns  for every column, so you can both set search and index  analyzers for a field.

**Comment by ballerupgis** [comment]
Looking forward to this upgrade

**Comment by mapcentia** [comment]
You can now customize the map. There is a new button called "Mapping". 

Any analyzers set in /var/www/geocloud2/app/conf/elasticsearch_settings.json are available in the Mapping dialog. See here for an example settings: https://gist.github.com/mapcentia/d4a3893649e12100549f
