### ISSUE TITLE
Index PostGIS POINT as geo_point in ElasticSearch

### ISSUE THREAD

**Issue by ballerupgis** [mapcentia/geocloud2#18]
Can you make it possible to index PostGIS (multi)point as geo_point instead of geo_shape in ElasticSearch?

**Comment by mapcentia** [comment]
Yes, geo_point will be implemented.

**Comment by mapcentia** [comment]
geo_point is now default for POINT geometry. Also see https://github.com/mapcentia/geocloud2/issues/17
