### ISSUE TITLE
Transform points to EPSG:4326 when indexing in ES

### ISSUE THREAD

**Issue by baffioso** [mapcentia/geocloud2#22]
Is it possible to transform points to EPSG:4326 when indexing in ElasticSerach? Seems like it keeps the original EPSG from PostGIS, which only compatible with tilemaps in Kibana when EPSG is 4326.

**Comment by mapcentia** [comment]
Geometry is transformed to 4326 when indexing. If it doesn't its a bug.

**Comment by baffioso** [comment]
Will test again and return

**Comment by baffioso** [comment]
Its working
