### ISSUE TITLE
WFS GetCapabilities takes long time for schemas with many (large) tables

### ISSUE THREAD

**Issue by baffioso** [mapcentia/geocloud2#23]
When loading WFS in QGIS it takes long time to GetCapabilities from schemas with many large tables. Is it possible to speed up this process?

**Comment by mapcentia** [comment]
Yes, its because the extent for each geometry is calculated. ST_EstimatedExtent can be used instead, which is very fast, but not so accurate. Also a setting with a static extent for all geometries can be added to the config.

**Comment by mapcentia** [comment]
Now ST_EstimatedExtent is used. If extent can't be calculated, a XML comment is inserted:
