### ISSUE TITLE
Load table structure from Materialized view

### ISSUE THREAD

**Issue by baffioso** [mapcentia/geocloud2#25]
I get the message "Could not load table structure" when selecting a materialized view in the Database tab. Is it possible to get this information?

**Comment by mapcentia** [comment]
Column introspecting is done with information_schema.columns, which is SQL standard and therefore not comprises not standard Materialized views. An idea is to switch the column introspecting for Materialized views to the catalog tables.

**Comment by mapcentia** [comment]
Column introspecting is now done in the catalog tables, so GC2 fully supports materialized views (both with and without geometry columns). Then creating a view from Admin, the option of creating as materialized is added. In Database grid and Map layertree each layer are now shown with a color code for neither Table, Foreign table, View or Materialized view.
