### ISSUE TITLE
hooks for specific events?

### ISSUE THREAD

**Issue by JosefAssad** [mapcentia/geocloud2#26]
This is probably non-trivial to implement, but for the sake of having a space to discuss it: it would be very useful to have facilities to execute code when certain events happen.

Example: when a table is updated or added, pass its metadata to a script which pushes a page to a MediaWiki instance.

I see GC2 as being the authoritative source for data concerning geodata tables in a larger and complex systems portfolio, and having this type of facility would allow for online metadata propagation throughout the architecture rather than (as I currently do) through batch updates from the API.

I imagine elasticsearch could also be coaxed into this, but that introduces the tradeoff of making it a harder dependency.

Thoughts?

**Comment by mapcentia** [comment]
One approach would be to define insert, update and delete events on the metadata table. The events will then call a custom RESTful service (POST, UPDATE, and DELETE) with the metadata as payload. And the service then calls MediaWiki.

The service URL could be set in the GC2 config. Also more than one service could be set like this:

$eventServices = ["http://my_domain/MediaWiki","http://my_domain/CKAN"]

**Comment by JosefAssad** [comment]
I like a lot the idea of being consumer-agnostic. I can already think of another system that would like to read GC2 metadata. :) (Cc @mariushart)

All the use cases I can think of offhand are covered by inser/update/delete on the metadata, but for the sake of thinking defensively: would it be smart to "generify" the source event also? I'm assuming (happy to be corrected) these are psql triggers, so maybe in the config it might look like:

    $eventServices = [{'Event': 'A', 'Service': 'X'}, {'Event': 'B', 'Service': 'Y'}]

You never know, there's crazy people out there with crazy use cases.

NB: a "No" is fine, just thinking defensive architecture.

**Comment by mapcentia** [comment]
It could be psql triggers using NOTIFY/LISTEN. A deamon (easily written in Node.js) could listen to the psql notifications and calling the script. Using NOTIFY/LISTEN makes it run async so network lag doesn't block the db transactions.

But shouldn't:

    $eventServices = [{'Event': 'A', 'Service': 'X'}, {'Event': 'B', 'Service': 'Y'}]

be like this:

    $eventServices = [{'Event': 'A', 'Service': ['X', 'Y']}, {'Event': 'B', 'Service': ['Z']}]

Or do I misunderstand you?

**Comment by JosefAssad** [comment]
Yeah that's even better. :)

**Comment by mapcentia** [comment]
This enhancement will roll out in January / February where the CKAN hook is now scheduled.
