### ISSUE TITLE
CKAN integration

### ISSUE THREAD

**Issue by JosefAssad** [mapcentia/geocloud2#27]
In Ballerup, a MediaWiki instance is used to display GC2 tables as you know.

We have a need to include the value of the "free text" field under the Semantic templates in the data which GC2 pushes to opendata.dk's CKAN, so we're interested in learning a bit about your technical plans for the GC2 -> CKAN integration.
Is it possible for you to describe this integration so we can figure out how this Mediawiki content can be weaved in?
Cc @clockend @baffioso

**Comment by JosefAssad** [comment]
After discussion with Ballerup our instinct is, that the simplest approach might be for the GC2-to-CKAN function to pull in documentation from mediawiki.

Do you agree that this would be the simplest option? We are currently not married to a specific solution, just looking for the path of least resistance.

Accessing per-table documentation is made a lot simpler after [this](https://github.com/JosefAssad/SeMaWi/issues/62) was implemented since the URL to the documentation page can be programmatically constructed from the table's UUID.

The format of the documentation is still up for discussion. CKAN appears to parse Markdown for things like description fiields, so one option is to use [pandoc](http://pandoc.org/) to convert Wikitext to Markdown before pushing it to opendata.dk.

Thoughts?

**Comment by mapcentia** [comment]
The GC2 -> CKAN integration is actual ready for use. GC2 now has a build in CKAN client with an API: http://my_gc2.com/api/v1/ckan/my_database?id=table_uuid&host="http://my_gc2.com" The host param is used to set the URL for ressources in CKAN. Also available is a Node.js daemon, which can listen on changes in the GC2 metadata and call the API. [Here is an example of a GC2/CKAN dataset] (http://geofyn-ckan.mapcentia.com/dataset/645ca298-9020-44cb-8e75-a92f15df6120)

**Comment by JosefAssad** [comment]
Ah so you call that CKAN client API and it triggers GC2 to push tables to CKAN?

As mentioned in https://github.com/JosefAssad/SeMaWi/issues/95 I agree it's ideal to weave mediawiki-based content in what the GC2 client sends to CKAN. I also agree the field "Beskrivelse" is a good location.

One challenge is that mediawiki does not use markdown; it uses its own format Wikitext which predates markdown. Perhaps if the GC2 client pulls mediawiki-based content through [pandoc](http://pandoc.org/)?
