### ISSUE TITLE
Cannot load "Map client" on OS X with Docker

### ISSUE THREAD

**Issue by snario** [mapcentia/geocloud2#28]
I get the following error and the page does not load (blank) when trying to load the map client on OS X using the latest `geocloud2` docker image:

![screen shot 2016-02-15 at 10 33 45 pm](https://cloud.githubusercontent.com/assets/1933029/13066479/5633d948-d434-11e5-885c-50e78071cfe0.png)

I have tried setting the hostname appropriately in case that makes a difference but not luck -- this page doesn't seem to work properly

**Comment by mapcentia** [comment]
Could you try to "Save extent" on public?
<img width="440" alt="administration" src="https://cloud.githubusercontent.com/assets/3850918/13069970/17b67874-d489-11e5-8713-8b6fcac47acb.png">

**Comment by snario** [comment]
Hi @mapcentia, after clicking "Save extent" it worked now. I guess this is a requirement to get it started? In any case thanks for the help! :)
