### ISSUE TITLE
Select multiple features in a layer (both shared maps and in admin interface)

### ISSUE THREAD

**Issue by jimmykirk** [mapcentia/geocloud2#33]
Allow users to use a user-drawn bounding box to create a selection of multiple features for the purpose of viewing them in a data grid OR passing them to another application as an array or json object.

**Comment by baffioso** [comment]
+1
Den 5. jun. 2016 12.45 AM skrev "jimmykirk" <notifications@github.com>:

**Comment by mapcentia** [comment]
This feature is actual a part of the new [Vidi project](https://github.com/mapcentia/vidi). The Vidi project is scheduled to have it first beta ready here in June.
<img width="1256" alt="screen shot 2016-06-07 at 10 14 23" src="https://cloud.githubusercontent.com/assets/3850918/15850579/0f1b0c30-2c99-11e6-9f2c-65fbf8a8b682.png">
