### ISSUE TITLE
Corrupted GC2 VMDK zip file

### ISSUE THREAD

**Issue by MBalazs90** [mapcentia/geocloud2#40]
I downloded the virtual box zipped file, then I tried to unzip it (with WinRar), but it always fails. The zip file is corrupted.

**Comment by mapcentia** [comment]
Try with this one: Could you try with this one: http://geocloud2-images.s3-accelerate.amazonaws.com/GC2+Quick+Start.vmdk.7z

Could you use 7-Zip for unzipping?
