### ISSUE TITLE
Hi GC2

### ISSUE THREAD

**Issue by mileslee1987** [mapcentia/geocloud2#52]
Hi GC2,

Would you please help give an example, when we upload data into GC2, how to generate WMS/WFS link and use it ? Where to find the endpoins ?

**Comment by mapcentia** [comment]
@mileslee1987 Take a look here: http://mapcentia.screenstepslive.com/s/en/m/35406/l/346780-upload-of-vector-files
After upload, click the Service button and you can grab service URLs and set a HTTP Auth password for WFS and WMS. See image:
![image](https://user-images.githubusercontent.com/3850918/48764962-70c31600-ecb1-11e8-95ff-afb405207af5.png)

**Comment by mileslee1987** [comment]
Thanks mapcentia, but with that link, do we need to provide any query string like that in Mapserver or Geoserver ? Would you mind give any tips ? thank you very much.
