### ISSUE TITLE
Cannot start service gc2core

### ISSUE THREAD

**Issue by TimJMartin** [mapcentia/geocloud2#59]
I have followed the instructions to run GC2 and Vidi using Docker and when I run docker-compose up I get the following error:

I am on a Windows 10 laptop using Docker Desktop version 2.0.0.3

```
Creating gc2_vidi_1     ... done
Creating gc2_postgis_1 ...
Creating gc2_mapcache_1 ...
Creating gc2_gc2core_1  ... error

Creating gc2_postgis_1  ... done
Creating gc2_mapcache_1 ... done
ror

ERROR: for gc2core  Cannot start service gc2core: driver failed programming external connectivity on endpoint gc2_gc2core_1 (dce42a608ddd23636235a5cfb4187f713020aeebd07e3dc0999bc3991f6440d5): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8080:tcp:172.18.0.2:80: input/output error
ERROR: Encountered errors while bringing up the project.
```

I am not sure how to resolve this issue and get GC2 launched.

Thanks for your help

**Comment by mapcentia** [comment]
@TimJMartin I think its a Windows related problem. I'll investigate.

**Comment by amruthkiran94** [comment]
Yes, just to add I'm facing the same issue on Windows.
Docker:  18.09.2, build 6247962
Any updates?

**Comment by mapcentia** [comment]
I believe this is a Docker for Windows thing. I'm not able to test.
