### ISSUE TITLE
Sub user seeing layers it shouldn't

### ISSUE THREAD

**Issue by TimJMartin** [mapcentia/geocloud2#61]
I am trying out GC2 using the online hosted  version and created a new account (peterrabbit) and uploaded two files (national parks and airports). I then created two sub users (without their own schemas).

In the admin account I then clicked on privliges and set that one user could see both and one user could only see one layer.

I then logged into GC2 in Incognito mode and the second user could see both layers in Vidi. I could also see both layers in the WFS in QGIS.

The strange thing is that when I go to the database view using the second user credentials I only see one of the layers - which is correct.

below are some images that show what is happening?

Maybe I am not setting something correctly as it partly works. Could you please help?

![AdminDashboard](https://user-images.githubusercontent.com/8383616/58906598-31678e80-8704-11e9-8093-f37e73b864f0.PNG)
![Privileges](https://user-images.githubusercontent.com/8383616/58906596-30cef800-8704-11e9-9c35-d32180cb08d8.PNG)
![SeeAirports](https://user-images.githubusercontent.com/8383616/58906597-31678e80-8704-11e9-84b7-712a19385ec9.PNG)

![InWFS](https://user-images.githubusercontent.com/8383616/58906600-31678e80-8704-11e9-96be-313c197c1d58.PNG)
![NoAirports](https://user-images.githubusercontent.com/8383616/58906601-31678e80-8704-11e9-8f62-e52a4ccc1fcc.PNG)

**Comment by TimJMartin** [comment]
Just to add I am trying to enable some users to see all layers and then some users can only see some layers. And no user should have write or be able to edit

**Comment by mapcentia** [comment]
Sorry for the late reply. You have to set the Database tab->Authentication to `Read/write` on the layers, which should only be visible for the sub-users.
![image](https://user-images.githubusercontent.com/3850918/60423453-8c4eb180-9bee-11e9-8b6d-1a11f10f9b25.png)

In WFS GetCapabilities you'll always see all layers, but you need to authenticate users when reading the layer.
