### ISSUE TITLE
This browser does not support Service Workers, some features may be unavailable

### ISSUE THREAD

**Issue by khalilgh3** [mapcentia/geocloud2#69]
hi there
I want to connect vidi and I see layers but it error
This browser does not support Service Workers, some features may be unavailable.
layers gc2 don't show in vidi.

**Comment by mapcentia** [comment]
You need a browser that supports Service Workers

**Comment by GirishVC86** [comment]
In google chrome browser go to  chrome://flags/#unsafely-treat-insecure-origin-as-secure
**Enable** _Insecure origins treated as secure_
Add your IP / Domain where it is hosted like http://192.168.0.1
This will do the work
