### ISSUE TITLE
Error when assigning role to sub-user for a layer with workflow management activated:

### ISSUE THREAD

**Issue by gjsa73** [mapcentia/geocloud2#73]
Uncaught Error: Cannot use object of type stdClass as array in /var/www/geocloud2/app/models/Layer.php:751 Stack trace: #0 /var/www/geocloud2/app/controllers/Layer.php(137): app\models\Layer->updateRoles(Array) #1 /var/www/geocloud2/app/inc/Route.php(79): app\controllers\Layer->put_roles(Array) #2 /var/www/geocloud2/public/index.php(252): app\inc\Route::add('controllers/Lay...') #3 {main} thrown

**Comment by mapcentia** [comment]
Fixed
