### ISSUE TITLE
Initial setup error

### ISSUE THREAD

**Issue by mdomox** [mapcentia/geocloud2#75]
1. Cloned dockerfiles. 
2.Run docker-compose up 
3. Register the first user: PDOException Error: Authentication failed for user gc2

![Screenshot from 2019-10-15 23-52-21](https://user-images.githubusercontent.com/2255012/66869085-45bb7200-efa7-11e9-9bec-a7b521ed9134.png)

**Comment by mapcentia** [comment]
@mdomox Please pull the latest `mapcentia/gc2core` og `mapcentia/vidi` images. And make sure, that your `dockerfiles` repo is up-to-date

**Comment by mdomox** [comment]
@mapcentia mapcentia/gc2core returns a 404 page. 

Moreover, docker bundle already includes vidi and gc2core. You mean to replace those inside the docker bundle with updated ones?

**Comment by mdomox** [comment]
@mapcentia pointed git to master of mapcentia: git clone https://github.com/mapcentia/dockerfiles.git

The issue remains. PDOException Error: Authentication failed for user gc2. 

postgis_1  | 2019-11-01 17:48:04.282 UTC [88] gc2@mapcentia FATAL:  password authentication failed for user "gc2"
postgis_1  | 2019-11-01 17:48:04.282 UTC [88] gc2@mapcentia DETAIL:  Password does not match for user "gc2".
postgis_1  |    Connection matched pg_hba.conf line 5: "host    all             gc2             0.0.0.0/0                                                                                                                                                password"
gc2core_1  | [01-Nov-2019 17:48:04] WARNING: [pool www] child 65 said into stderr: "NOTICE: PHP message: PHP                                                                                                                                  Fatal error:  Uncaught PDOException: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "gc2""

**Comment by mapcentia** [comment]
@mdomox Just to make sure: Are you using this docker-compose file: https://github.com/mapcentia/dockerfiles/tree/master/docker-compose/local/gc2

**Comment by mdomox** [comment]
@mapcentia  Yes.

**Comment by renzoepolo** [comment]
Is there a solution for this error? The same thing happened to me. Thanks

**Comment by mapcentia** [comment]
Closing this one because it's related to deployment of the stack and not to GC2 source code
