### ISSUE TITLE
Use of undefined constant PGBOUNCER_CONFIGURATION

### ISSUE THREAD

**Issue by aim8526** [mapcentia/geocloud2#76]
![image](https://user-images.githubusercontent.com/34396096/67661514-762be480-f987-11e9-831f-d0465652dda0.png)

I got the above error while signup.

**Comment by mapcentia** [comment]
Is your `dockerfiles` repo up-to-date? And do you have pulled the latest mapcentia/gc2core image? 

The `PGBOUNCER_CONFIGURATION`  var in `/app/conf/Connection.php` should be replaced:
https://github.com/mapcentia/dockerfiles/blob/master/gc2core/stable/entrypoint.sh#L88
with `false` from:
https://github.com/mapcentia/dockerfiles/blob/master/docker-compose/local/gc2/gc2.env#L7
