### ISSUE TITLE
WFS service should return correct status

### ISSUE THREAD

**Issue by giovanniborella** [mapcentia/geocloud2#78]
When querying the WFS-implementation GC2 should return the correct error-code.

Even if the service throws an exception, the http-statuscode is still 200 as per screenshot:
![billede](https://user-images.githubusercontent.com/18160930/70532211-ddc47a80-1b56-11ea-9139-3659b940dec5.png)

should return 500 for server error

**Comment by mapcentia** [comment]
@giovanniborella Not returning 200 will break things in e.g. MapInfo, which will not show the Expection message when getting other than 200. So I believe the right thing is to return an expections with code 200.
