### ISSUE TITLE
First boot error

### ISSUE THREAD

**Issue by renzoepolo** [mapcentia/geocloud2#83]
When registering for the first time, I have the following error:

```
[Mon Oct 26 22:53:19.777279 2020] [proxy_fcgi:error] [pid 97:tid 140052724434688] [client 172.18.0.1:55594] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[08006] [7] could not translate host name "postgis" to address: Name or service not known in /var/www/geocloud2/app/inc/Model.php:244\nStack trace:\n#0 /var/www/geocloud2/app/models/User.php(170): app\\inc\\Model->execQuery('SELECT COUNT(*)...')\n#1 /var/www/geocloud2/app/api/v2/User.php(109): app\\models\\User->createUser(Array)\n#2 /var/www/geocloud2/app/inc/Route.php(81): app\\api\\v2\\User->post_index(Array)\n#3 /var/www/geocloud2/public/index.php(217): app\\inc\\Route::add('api/v2/User', Object(Closure))\n#4 {main}\n  thrown in /var/www/geocloud2/app/inc/Model.php on line 244', referer: http://192.168.1.107:8080/dashboard/sign-up


172.18.0.1 - - [26/Oct/2020:22:53:19 +0000] "POST /api/v2/user HTTP/1.1" 500 1027 "http://192.168.1.107:8080/dashboard/sign-up" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36"
```

**Comment by mapcentia** [comment]
@renzoepolo `could not translate host name "postgis" to address` means that the container "postgis" can't be discovered from inside the container "gc2core". Again this means, that the two containers are not on the same Docker network. The solutions is to connect them to the same network.

**Comment by renzoepolo** [comment]
By default the containers are connected in the following networks:
- gc2_vidi_1: host
- gc2_gc2core_1: gc2_default
- gc2_postgis_1: gc2_internal
Is this configuration correct?

**Comment by mapcentia** [comment]
If you use this docker-compose file: https://github.com/mapcentia/dockerfiles/blob/master/docker-compose/local/gc2/docker-compose.yml
then both the gc2 and postgis will be connected to gc2_internal
