### ISSUE TITLE
support for postgis 3.0

### ISSUE THREAD

**Issue by giovanniborella** [mapcentia/geocloud2#86]
This list is clearly incomplete, but heads up:

* raster is broken out of main postgis, so `CREATE EXTENSION postgis_raster;` is also needed when creating databases.
* Currently the logic to differ `ST_Force_2D`/`ST_Force2D` cannot handle `3.0`. Maybe something like this to keep backwards compatibility:

``` php
        // If the backend is running 2.0.X or lower, use ST_Force_2D - else use ST_Force2D
        if ((int)$bits[0] < 3 AND (int)$bits[0] = 0) {
            $ST_Force2D = "ST_Force_2D";
        } else {
            $ST_Force2D = "ST_Force2D";
        }
```

The logic is here:
* https://github.com/mapcentia/geocloud2/blob/ac1dde80f85e09374ce6a53a0637f564cb387c89/app/models/Sql.php#L73
* https://github.com/mapcentia/geocloud2/blob/774a45f9e505e10678baf53dddd4ed099e36a39f/app/models/Sql_to_es.php#L114

I'm guessing there is more. Will

**Comment by mapcentia** [comment]
It should be this:
```php
if ((int)$bits[0] < 3 && (int)$bits[1] === 0) {
      $ST_Force2D = "ST_Force_2D";  // In case of PostGIS 2.0.x
  } else {
      $ST_Force2D = "ST_Force2D"
  }
```
Implemented in https://github.com/mapcentia/geocloud2/commit/fdeddcfa647a8f509a1a1d94e68214f23f48ea2a
