### ISSUE TITLE
Can't run migrations if variables in Connection.php is set as env

### ISSUE THREAD

**Issue by BoMarconiHenriksen** [mapcentia/geocloud2#91]
If the variables in Connection.php is set as environment variables in the image and therefore Connection.php is empty. It is not possible to run the migrations.

**Comment by mapcentia** [comment]
I guess this only apply to running the app/migration/run.php script? And not using the api/v3/admin API?

**Comment by BoMarconiHenriksen** [comment]
This is when running the app/migration/run.php script in the image. I have not tried it with api/v3/admin API.
